spring.application.name=user-service

spring.security.user.name=user
spring.security.user.password=1234

server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/authservice
spring.datasource.username=root
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtSecret=RHVtbXlKZXRQcm9qZWN0U2VjcmV0S2V5MTIzNDU2Nzg5MA==

spring.app.jwtExpirationMs=86400000



eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
